import {isDeepStrictEqual} from 'node:util';
import express,{type Request,type Response,type NextFunction} from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import sharp from 'sharp';
import {z,ZodError} from 'zod';
import {randomUUID,randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {mkdirSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {resolve,join,basename} from 'node:path';
import {openStore} from './store.js';
import {newCase,demoCase} from './demo.js';
import {renderReport} from './report.js';
import {runWorkflow,getAiCapabilities,executeAgentTool,setVerifiedLegalSources} from './ai/index.js';
import {createMcpRouter} from './mcp/index.js';
import {createAlipayRouter} from './integrations/alipay.js';
import {agentIds,type CaseRecord,type User,type BusinessServices,type AgentOutput,type AgentRun,type WorkflowRequest} from '../shared/types.js';
export type AppOptions={dataDir?:string;publicOrigin?:string;secureCookies?:boolean;disableRateLimit?:boolean};
class HttpError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
const bad=(message:string)=>new HttpError(400,'INVALID_INPUT',message);const notFound=()=>new HttpError(404,'NOT_FOUND','案件或记录不存在');
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');const now=()=>new Date().toISOString();const uid=()=>randomUUID();
const str=z.string().trim().min(1).max(6000),text=z.string().max(12000);const agent=z.enum(agentIds);const tone=z.enum(['gentle','firm','formal']);
const extractSchema=z.object({merchant:z.string().max(200).optional(),amount:z.string().max(100).optional(),date:z.string().max(100).optional(),product:z.string().max(500).optional(),orderNumber:z.string().max(200).optional(),refundStatus:z.string().max(500).optional(),quotes:z.array(z.string().max(6000)).max(30).optional(),uncertainties:z.array(z.string().max(1000)).max(30).optional()}).strict();
const credential=z.object({email:z.string().email().max(254).transform(s=>s.toLowerCase()),password:z.string().min(12).max(128),name:z.string().trim().min(1).max(80).optional()}).strict();
export function createApp(options:AppOptions={}){
 const app=express();const dataDir=resolve(options.dataDir||process.env.DATA_DIR||'data');const files=join(dataDir,'files');mkdirSync(files,{recursive:true});const store=openStore(dataDir);app.locals.db=store.db;const origin=options.publicOrigin||process.env.PUBLIC_ORIGIN||'http://127.0.0.1:5173';const secure=options.secureCookies??origin.startsWith('https:');const running=new Map<string,{controller:AbortController,runId:string,userId:string,roleRuns:Set<string>}>();
 const legalSources=JSON.parse(readFileSync(resolve('docs/integrations/legal-sources.json'),'utf8')) as {title:string;url:string;checkedAt:string;note:string}[];setVerifiedLegalSources(legalSources);
 const capabilities=()=>({...getAiCapabilities(),mode:getAiCapabilities().aiConfigured?'live' as const:'unconfigured' as const,alipayConfigured:process.env.ALIPAY_ENABLED==='true'&&!!process.env.ALIPAY_APP_ID&&!!process.env.ALIPAY_PRIVATE_KEY&&!!process.env.ALIPAY_PUBLIC_KEY&&!!process.env.PUBLIC_ORIGIN,mcpEnabled:process.env.MCP_ENABLED!=='false',legalSources});
 app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:'],connectSrc:["'self'"],objectSrc:["'none'"],frameAncestors:["'none'"]}},crossOriginEmbedderPolicy:false}));app.use(express.json({limit:'200kb'}));
 if(!options.disableRateLimit)app.use('/api',rateLimit({windowMs:60000,limit:180,standardHeaders:'draft-7',legacyHeaders:false}));
 function tokenUser(token:string):User|null{const row=store.db.prepare('SELECT user_id FROM tokens WHERE hash=?').get(hash(token)) as any;return row?store.user(row.user_id):null;}
 app.use((req,res,next)=>{const authorization=req.headers.authorization;const bearer=/^Bearer (\S+)$/i.exec(authorization||'')?.[1];let user:User|null=null;if(authorization){user=bearer?tokenUser(bearer):null;res.locals.invalidAuthorization=!user;res.locals.bearer=!!user;}else{const cookie=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('whyduck_session='))?.slice(16);if(cookie){const row=store.db.prepare('SELECT user_id FROM sessions WHERE hash=? AND expires>?').get(hash(cookie),Date.now()) as any;user=row?store.user(row.user_id):null;res.locals.sessionHash=hash(cookie);}}res.locals.user=user;res.locals.alipayLinked=user?!!(store.db.prepare('SELECT alipay FROM users WHERE id=?').get(user.id) as any)?.alipay:false;next();});
 app.use('/api',(req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method)||res.locals.bearer||req.path==='/mcp')return next();if(req.header('X-WhyDuck-Client')!=='web'||(req.header('Origin')&&req.header('Origin')!==origin))return next(new HttpError(403,'CSRF_REJECTED','写请求需要合法客户端与允许的来源'));next();});
 function auth(req:Request,res:Response,next:NextFunction){if(!res.locals.user||res.locals.invalidAuthorization)return next(new HttpError(401,'UNAUTHORIZED','请先登录或提供有效账户令牌'));next();}
 function user(res:Response):User{return res.locals.user as User;}
 function getCase(owner:string,id:string){const c=store.get(owner,id);if(!c)throw notFound();return c;}
 function activeGuard(c:CaseRecord){if(running.has(c.id))throw new HttpError(409,'CASE_BUSY','案件正在分析，请先取消或等待完成');}
 function revise(c:CaseRecord){c.factRevision++;c.drafts.forEach(d=>d.stale=true);}
 function save(c:CaseRecord,res:Response,status=200){store.save(c);res.status(status).json({case:c});}
 function requireRef(c:CaseRecord,evidenceId?:string,quote?:string){if(quote&&!evidenceId)throw bad('引文必须关联证据');if(evidenceId){const e=c.evidence.find(e=>e.id===evidenceId);if(!e)throw bad('材料不存在');if(quote){const raw=e.sourceText||(e.confirmed?e.extraction?.quotes?.join('\n'):undefined);if(!raw?.includes(quote))throw bad('引文未在已核查原文中找到');}}}
 const services:BusinessServices={getCase,listCases:owner=>store.list(owner),executeTool:async(name,input,ctx)=>{const c=getCase(ctx.userId,ctx.caseId);if(name!=='extract_purchase_evidence')return executeAgentTool(name,input,c,ctx.signal);const eid=z.string().min(1).parse(input.evidenceId);const e=c.evidence.find(e=>e.id===eid);if(!e)throw bad('材料不存在');if(e.sourceType==='text'||e.confirmed)return executeAgentTool(name,input,c,ctx.signal);activeGuard(c);if(c.demo)throw new HttpError(409,'DEMO_ONLY','示例材料不能调用真实模型');if(!getAiCapabilities().aiConfigured)throw new HttpError(503,'AI_UNCONFIGURED','尚未配置千问视觉模型');if(!services.getUser(ctx.userId).aiConsent)throw new HttpError(403,'AI_CONSENT_REQUIRED','请先在设置中同意第三方模型处理');const controller=new AbortController();const signal=ctx.signal?AbortSignal.any([ctx.signal,controller.signal]):controller.signal;const workflowId=uid();running.set(c.id,{controller,runId:workflowId,userId:c.ownerId,roleRuns:new Set()});const requestContext={message:'仅提取指定原始消费凭证，extractions中使用指定证据ID，字段为待核对建议；不要生成引用未确认图中文字的citations。',mode:'direct' as const,target:'detective' as const};try{const bytes=await sharp(readFileSync(join(files,c.id,e.id)),{limitInputPixels:40000000}).rotate().resize({width:1500,height:1500,fit:'inside',withoutEnlargement:true}).toFormat(e.mime==='image/png'?'png':e.mime==='image/jpeg'?'jpeg':'webp').toBuffer();await runWorkflow(c,{...requestContext,runId:workflowId,signal,images:[{evidenceId:e.id,dataUrl:`data:${e.mime};base64,${bytes.toString('base64')}`}]},{emit:event=>{if(event.type==='start'&&event.runId)running.get(c.id)?.roleRuns.add(event.runId)},persist:async(output,run)=>persistAgent(c,output,run,requestContext)});if(!e.extraction)throw new HttpError(502,'EXTRACTION_MISSING','模型未返回指定材料提取结果');return {evidenceId:e.id,extraction:e.extraction,status:'proposed',requiresHumanReview:true,runId:c.runs.at(-1)?.id,usage:c.messages.at(-1)?.result?.usage};}finally{running.delete(c.id);}},getUser:id=>{const u=store.user(id);if(!u)throw new HttpError(401,'UNAUTHORIZED','账户不存在');return u;},authenticateToken:tokenUser,getCapabilities:capabilities,linkAlipay:(owner,alipay)=>{try{store.db.prepare('UPDATE users SET alipay=? WHERE id=?').run(alipay,owner);}catch{throw new HttpError(409,'ALIPAY_ALREADY_LINKED','此支付宝身份已关联其他账户，未修改关联');}},unlinkAlipay:owner=>store.db.prepare('UPDATE users SET alipay=NULL WHERE id=?').run(owner)};app.locals.services=services;
 function session(res:Response,id:string){const value=randomBytes(32).toString('hex');store.db.prepare('INSERT INTO sessions(hash,user_id,expires) VALUES(?,?,?)').run(hash(value),id,Date.now()+7*86400000);res.cookie('whyduck_session',value,{httpOnly:true,sameSite:'lax',secure,maxAge:7*86400000,path:'/'});}
 app.get('/api/health',(_req,res)=>res.json({ok:true,storage:'sqlite',version:'1.0.0'}));
 app.get('/api/session',(_req,res)=>res.json({user:res.locals.user||null,capabilities:capabilities()}));
 const authLimiter=rateLimit({windowMs:15*60000,limit:25,standardHeaders:'draft-7',legacyHeaders:false});if(!options.disableRateLimit)app.use('/api/auth',(req,res,next)=>{if(req.method==='POST'&&['/register','/login','/tokens'].includes(req.path))return authLimiter(req,res,next);next();});
 app.post('/api/auth/register',(req,res)=>{const p=credential.parse(req.body);const salt=randomBytes(16).toString('hex');const password=salt+':'+scryptSync(p.password,salt,64).toString('hex');const id=uid();try{store.db.prepare('INSERT INTO users(id,email,name,password,created) VALUES(?,?,?,?,?)').run(id,p.email,p.name||p.email.split('@')[0],password,now());}catch{throw new HttpError(409,'EMAIL_EXISTS','邮箱已注册');}session(res,id);res.status(201).json({user:store.user(id)});});
 app.post('/api/auth/login',(req,res)=>{const p=credential.omit({name:true}).parse(req.body);const row=store.db.prepare('SELECT * FROM users WHERE email=?').get(p.email) as any;const salt=row?.password.split(':')[0]||'dummy-login-salt';const expected=row?Buffer.from(row.password.split(':')[1],'hex'):Buffer.alloc(64);const actual=scryptSync(p.password,salt,64);if(!row||!timingSafeEqual(actual,expected))throw new HttpError(401,'INVALID_CREDENTIALS','邮箱或密码错误');session(res,row.id);res.json({user:store.publicUser(row)});});
 app.post('/api/auth/logout',(req,res)=>{if(res.locals.sessionHash)store.db.prepare('DELETE FROM sessions WHERE hash=?').run(res.locals.sessionHash);res.clearCookie('whyduck_session',{path:'/'});res.json({ok:true});});
 app.patch('/api/profile',auth,(req,res)=>{const p=z.object({name:z.string().trim().min(1).max(80).optional(),aiConsent:z.boolean().optional()}).strict().parse(req.body);const u=user(res);store.db.prepare('UPDATE users SET name=?,consent=? WHERE id=?').run(p.name??u.name,p.aiConsent===undefined?Number(u.aiConsent):Number(p.aiConsent),u.id);res.json({user:store.user(u.id)});});
 app.post('/api/auth/tokens',auth,(req,res)=>{const p=z.object({label:z.string().trim().min(1).max(80)}).strict().parse(req.body);const token='wd_'+randomBytes(32).toString('hex'),id=uid();store.db.prepare('INSERT INTO tokens(id,hash,user_id,label,created) VALUES(?,?,?,?,?)').run(id,hash(token),user(res).id,p.label,now());res.status(201).json({token,id});});
 app.get('/api/auth/tokens',auth,(_req,res)=>res.json({tokens:store.db.prepare('SELECT id,label,created AS createdAt FROM tokens WHERE user_id=?').all(user(res).id)}));
 app.delete('/api/auth/tokens/:id',auth,(req,res)=>{store.db.prepare('DELETE FROM tokens WHERE id=? AND user_id=?').run(String(req.params.id),user(res).id);res.json({ok:true});});
 app.use('/api/mcp',createMcpRouter(services));app.use('/mcp',...(options.disableRateLimit?[]:[rateLimit({windowMs:60000,limit:90})]),(req,res,next)=>{if(req.header('Origin')&&req.header('Origin')!==origin)return next(new HttpError(403,'INVALID_ORIGIN','请求来源不允许'));next();},createMcpRouter(services));app.use('/api/alipay',createAlipayRouter(services));
 app.use('/api/cases',auth);
 app.get('/api/cases',(_req,res)=>res.json({cases:store.list(user(res).id)}));
 app.post('/api/cases',(req,res)=>{const p=z.object({title:z.string().trim().min(1).max(200),description:text.optional()}).strict().parse(req.body);save(newCase(user(res).id,p.title,p.description),res,201);});
 app.post('/api/cases/demo',(req,res)=>{const p=z.object({scenario:z.enum(['refund','contradiction','evidence-missing','continue'])}).strict().parse(req.body);save(demoCase(user(res).id,p.scenario),res,201);});
 app.get('/api/cases/:id',(req,res)=>res.json({case:getCase(user(res).id,req.params.id)}));
 app.patch('/api/cases/:id',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const p=z.object({title:z.string().trim().min(1).max(200).optional(),merchant:z.string().max(200).optional(),product:z.string().max(500).optional(),amount:z.string().max(100).optional(),purchaseDate:z.string().max(100).optional(),request:text.optional(),category:z.string().max(100).optional(),status:z.enum(['active','waiting','resolved','archived']).optional(),members:z.array(agent).max(6).optional()}).strict().parse(req.body);if(Object.keys(p).some(k=>!['title','status','members'].includes(k)))revise(c);Object.assign(c,p);c.members=[...new Set(['butler' as const,...c.members])];save(c,res);});
 function deleteFile(c:CaseRecord,id:string){const path=join(files,c.id,id);if(existsSync(path))rmSync(path);}
 app.delete('/api/cases/:id',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);if(req.body.confirmation!==c.id)throw bad('请确认删除正确案件');for(const e of c.evidence)deleteFile(c,e.id);const path=join(files,c.id);if(existsSync(path))rmSync(path,{recursive:true});store.db.prepare('DELETE FROM cases WHERE id=? AND owner_id=?').run(c.id,c.ownerId);store.audit(c.ownerId,c.id,'case_deleted');res.json({ok:true});});
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:1,fields:3,fieldSize:100000}}).single('file');
 app.post('/api/cases/:id/evidence',upload,async(req,res)=>{const c=getCase(user(res).id,String(req.params.id));activeGuard(c);if(c.evidence.length>=100)throw bad('每个案件最多100份材料');const id=uid();let bytes:Buffer,mime:string,filename:string,sourceText:string|undefined,sourceType:'image'|'text';if(req.file){const buffer=req.file.buffer;const isPng=buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const isJpg=buffer[0]===255&&buffer[1]===216&&buffer[2]===255;const isWebp=buffer.subarray(0,4).toString()==='RIFF'&&buffer.subarray(8,12).toString()==='WEBP';if(!isPng&&!isJpg&&!isWebp)throw bad('只接受真实PNG/JPG/WebP图片');const metadata=await sharp(buffer,{limitInputPixels:40000000}).metadata().catch(()=>{throw bad('图片内容损坏或超过像素限制')});if(!['png','jpeg','webp'].includes(metadata.format||''))throw bad('图片格式无效');mime=isPng?'image/png':isJpg?'image/jpeg':'image/webp';bytes=buffer;filename=basename(req.file.originalname.replace(/\\/g,'/')).replace(/[\u0000-\u001f]/g,'').slice(0,200)||'消费凭证';sourceType='image';}else{const p=z.object({sourceText:z.string().trim().min(1).max(100000),filename:z.string().trim().min(1).max(200)}).strict().parse(req.body);sourceText=p.sourceText;bytes=Buffer.from(sourceText);mime='text/plain';filename=basename(p.filename);sourceType='text';}const latest=getCase(user(res).id,c.id);activeGuard(latest);if(latest.evidence.length>=100)throw bad('每个案件最多100份材料');Object.assign(c,latest);mkdirSync(join(files,c.id),{recursive:true});writeFileSync(join(files,c.id,id),bytes,{flag:'wx'});const evidence={id,code:'E'+(Math.max(0,...c.evidence.map(e=>Number(e.code.slice(1))||0))+1),filename,mime,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),sourceType,...(sourceText?{sourceText}:{}),confirmed:false,createdAt:now()};c.evidence.push(evidence);revise(c);store.save(c);res.status(201).json({evidence,case:c});});
 app.get('/api/cases/:id/evidence/:eid/file',(req,res)=>{const c=getCase(user(res).id,req.params.id),e=c.evidence.find(e=>e.id===req.params.eid);if(!e)throw notFound();res.setHeader('Cache-Control','private, no-store');res.setHeader('Content-Type',e.mime==='text/plain'?'text/plain; charset=utf-8':e.mime);res.setHeader('X-Content-Type-Options','nosniff');res.send(e.sourceType==='text'?e.sourceText||'':readFileSync(join(files,c.id,e.id)));});
 app.patch('/api/cases/:id/evidence/:eid',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const e=c.evidence.find(e=>e.id===req.params.eid);if(!e)throw notFound();const p=z.object({extraction:extractSchema,confirmed:z.boolean()}).strict().parse(req.body);if(e.sourceType==='text')for(const q of p.extraction.quotes||[])if(!e.sourceText?.includes(q))throw bad('提取引文不是原文');e.extraction=p.extraction;e.confirmed=p.confirmed;for(const f of c.facts.filter(f=>f.evidenceId===e.id))f.status='proposed';revise(c);save(c,res);});
 app.delete('/api/cases/:id/evidence/:eid',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const e=c.evidence.find(e=>e.id===req.params.eid);if(!e)throw notFound();if(req.body.confirmation!==e.id)throw bad('请确认删除正确材料');deleteFile(c,e.id);c.evidence=c.evidence.filter(x=>x.id!==e.id);c.facts.forEach(f=>{if(f.evidenceId===e.id){f.status='proposed';delete f.evidenceId;delete f.quote;}});revise(c);save(c,res);});
 app.post('/api/cases/:id/facts',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const p=z.object({label:str,value:str,evidenceId:z.string().optional(),quote:str.optional()}).strict().parse(req.body);requireRef(c,p.evidenceId,p.quote);revise(c);c.facts.push({id:uid(),...p,status:'proposed',origin:'user',revision:c.factRevision});save(c,res,201);});
 app.patch('/api/cases/:id/facts/:fid',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const f=c.facts.find(f=>f.id===req.params.fid);if(!f)throw notFound();const p=z.object({label:str.optional(),value:str.optional(),status:z.enum(['proposed','confirmed']).optional()}).strict().parse(req.body);if(p.status==='confirmed')requireRef(c,f.evidenceId,f.quote);const changed=(p.value!==undefined&&p.value!==f.value)||(p.label!==undefined&&p.label!==f.label);Object.assign(f,p);if(changed)f.status='proposed';revise(c);f.revision=c.factRevision;save(c,res);});
 app.delete('/api/cases/:id/facts/:fid',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);if(!c.facts.some(f=>f.id===req.params.fid))throw notFound();c.facts=c.facts.filter(f=>f.id!==req.params.fid);revise(c);save(c,res);});
 app.post('/api/cases/:id/tasks',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const p=z.object({title:str,agentId:agent,priority:z.enum(['high','normal','low']),dueAt:z.string().datetime().optional(),status:z.enum(['proposed','pending'])}).strict().parse(req.body);c.tasks.push({id:uid(),...p,createdAt:now()});save(c,res,201);});
 app.patch('/api/cases/:id/tasks/:tid',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const t=c.tasks.find(t=>t.id===req.params.tid);if(!t)throw notFound();const p=z.object({title:str.optional(),dueAt:z.string().datetime().optional(),priority:z.enum(['high','normal','low']).optional(),status:z.enum(['proposed','pending','done']).optional()}).strict().parse(req.body);if(t.status==='proposed'&&p.status==='done')throw bad('待办需先确认才能完成');Object.assign(t,p);save(c,res);});
 app.delete('/api/cases/:id/tasks/:tid',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);if(!c.tasks.some(t=>t.id===req.params.tid))throw notFound();c.tasks=c.tasks.filter(t=>t.id!==req.params.tid);save(c,res);});
 app.post('/api/cases/:id/drafts',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const p=z.object({tone,text:str}).strict().parse(req.body);c.drafts.push({id:uid(),...p,factRevision:c.factRevision,stale:false,createdAt:now()});save(c,res,201);});
 app.patch('/api/cases/:id/drafts/:did',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);const d=c.drafts.find(d=>d.id===req.params.did);if(!d)throw notFound();const p=z.object({text:str,tone:tone.optional(),acknowledgeRevision:z.boolean().optional()}).strict().parse(req.body);d.text=p.text;if(p.tone)d.tone=p.tone;if(p.acknowledgeRevision){d.factRevision=c.factRevision;d.stale=false;}save(c,res);});
 app.delete('/api/cases/:id/drafts/:did',(req,res)=>{const c=getCase(user(res).id,req.params.id);activeGuard(c);if(!c.drafts.some(d=>d.id===req.params.did))throw notFound();c.drafts=c.drafts.filter(d=>d.id!==req.params.did);save(c,res);});
 app.get('/api/cases/:id/report',(req,res)=>{const c=getCase(user(res).id,req.params.id),format=z.enum(['markdown','html']).parse(req.query.format||'markdown');res.setHeader('Cache-Control','private, no-store');if(format==='html')res.setHeader('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'; base-uri 'none'");res.type(format==='html'?'html':'text/markdown').send(renderReport(c,format,req.query.redact!=='false'));});
 async function persistAgent(c:CaseRecord,output:AgentOutput,run:AgentRun,p:{message:string;mode:string;target?:string}){store.db.prepare('INSERT INTO run_context(id,case_id,data) VALUES(?,?,?)').run(run.id,c.id,JSON.stringify({message:p.message,mode:p.mode,target:p.target}));c.runs.push(run);if(run.status==='completed'){const factKey=(f:{label:string;value:string;evidenceId?:string;quote?:string})=>JSON.stringify([f.label,f.value,f.evidenceId||'',f.quote||'']);const seenFacts=new Set(c.facts.map(factKey));const newFacts=output.facts.filter(f=>{const key=factKey(f);if(seenFacts.has(key))return false;seenFacts.add(key);return true});const changedExtraction=output.extractions?.some(item=>{const e=c.evidence.find(e=>e.id===item.evidenceId);return e&&!e.confirmed&&!isDeepStrictEqual(e.extraction,item.data)});if(newFacts.length||changedExtraction)revise(c);c.messages.push({id:uid(),role:'agent',agentId:output.agentId,content:output.message,citations:output.citations,createdAt:now(),mode:'live',runId:run.id,result:output});for(const fact of newFacts)c.facts.push({id:uid(),...fact,status:'proposed',origin:'ai',revision:c.factRevision});if(output.agentId==='followup')for(const task of output.tasks){if(!c.tasks.some(existing=>existing.status!=='done'&&existing.title===task.title&&existing.agentId===task.agentId&&existing.priority===task.priority&&existing.dueAt===task.dueAt))c.tasks.push({id:uid(),...task,status:'proposed',createdAt:now()});}for(const draft of output.drafts)c.drafts.push({id:uid(),...draft,factRevision:c.factRevision,stale:false,createdAt:now()});for(const extracted of output.extractions||[]){const e=c.evidence.find(e=>e.id===extracted.evidenceId);if(e&&!e.confirmed){e.extraction=extracted.data;e.confirmed=false;}}c.members=[...new Set([...c.members,output.agentId])];}store.save(c);store.audit(c.ownerId,c.id,`agent_${run.agentId}_${run.status}`);}
 async function stream(req:Request,res:Response,c:CaseRecord,p:{message:string;target?:typeof agentIds[number];mode:'group'|'direct';requestId?:string},retry=false){
  activeGuard(c);if(c.demo)throw new HttpError(409,'DEMO_ONLY','示例案件不分析新材料，请创建真实案件');const workflowId=uid();
  if(!retry){if(p.requestId&&c.messages.some(m=>m.id===p.requestId))throw new HttpError(409,'DUPLICATE_REQUEST','该消息已经接收，请勿重复发送');c.messages.push({id:p.requestId||uid(),role:'user',content:p.message,citations:[],createdAt:now(),mode:'live',runId:workflowId});store.save(c);}
  if(!getAiCapabilities().aiConfigured)throw new HttpError(503,'AI_UNCONFIGURED','尚未配置千问模型，已保留用户消息，未生成分析');if(!user(res).aiConsent)throw new HttpError(403,'AI_CONSENT_REQUIRED','请先在设置中同意将本案材料发送给第三方模型处理');
  const controller=new AbortController();running.set(c.id,{controller,runId:workflowId,userId:c.ownerId,roleRuns:new Set()});res.status(200).set({'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders();const disconnect=()=>{if(!res.writableEnded)controller.abort(new Error('客户端断开连接'));};res.on('close',disconnect);const emit=(event:any)=>{if(event.type==='start'&&event.runId)running.get(c.id)?.roleRuns.add(event.runId);if(!res.destroyed&&!res.writableEnded)res.write(`data: ${JSON.stringify(event)}\n\n`);};emit({type:'route',runId:workflowId,members:p.target?[p.target]:['butler']});
  async function persist(output:AgentOutput,run:AgentRun){await persistAgent(c,output,run,p);}
  try{const images=await Promise.all(c.evidence.filter(e=>e.sourceType==='image'&&!e.confirmed).slice(0,8).map(async e=>({evidenceId:e.id,dataUrl:`data:${e.mime};base64,${(await sharp(readFileSync(join(files,c.id,e.id)),{limitInputPixels:40000000}).rotate().resize({width:1500,height:1500,fit:'inside',withoutEnlargement:true}).toFormat(e.mime==='image/png'?'png':e.mime==='image/jpeg'?'jpeg':'webp').toBuffer()).toString('base64')}`})));await runWorkflow(c,{message:p.message,target:p.target,mode:p.mode,runId:workflowId,signal:controller.signal,images},{emit,persist});}catch(error){if(!res.destroyed)emit({type:controller.signal.aborted?'cancelled':'error',runId:workflowId,message:error instanceof Error?error.message:'分析失败'});}finally{running.delete(c.id);res.removeListener('close',disconnect);if(!res.writableEnded)res.end();}
 }
 const msgSchema=z.object({message:z.string().trim().min(1).max(12000),target:agent.optional(),mode:z.enum(['group','direct']),requestId:z.string().uuid().optional()}).strict();
 app.post('/api/cases/:id/messages',async(req,res)=>{const c=getCase(user(res).id,req.params.id);const p=msgSchema.parse(req.body);if(p.mode==='direct'&&!p.target)throw bad('独立聊天必须指定角色');await stream(req,res,c,p);});
 app.post('/api/cases/:id/runs/:rid/cancel',(req,res)=>{const c=getCase(user(res).id,req.params.id);const current=running.get(c.id);if(!current||current.userId!==user(res).id)throw notFound();if(current.runId!==req.params.rid&&!current.roleRuns.has(req.params.rid))throw notFound();current.controller.abort(new Error('用户取消任务'));res.json({ok:true});});
 app.post('/api/cases/:id/retry',async(req,res)=>{const c=getCase(user(res).id,req.params.id);const p=z.object({runId:z.string().uuid()}).strict().parse(req.body);const failed=c.runs.find(r=>r.id===p.runId&&['failed','cancelled'].includes(r.status));if(!failed)throw bad('只能重试失败或已取消的任务');const context=store.db.prepare('SELECT data FROM run_context WHERE id=? AND case_id=?').get(failed.id,c.id) as any;if(!context)throw bad('缺少原始用户任务');const original=JSON.parse(context.data);await stream(req,res,c,{message:original.message,mode:'direct',target:failed.agentId},true);});
 app.use('/api',(_req,_res,next)=>next(notFound()));
 const staticDir=resolve('dist/client');if(existsSync(staticDir)){app.use(express.static(staticDir,{index:false}));app.get('/{*splat}',(_req,res)=>res.sendFile(join(staticDir,'index.html')));}
 app.use((error:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(res.headersSent){if(!res.writableEnded)res.end();return;}if(error instanceof HttpError){res.status(error.status).json({error:{code:error.code,message:error.message}});return;}if(error instanceof ZodError||error instanceof multer.MulterError||error instanceof SyntaxError){res.status(400).json({error:{code:'INVALID_INPUT',message:error instanceof multer.MulterError?'上传大小或格式不符合要求':'输入字段或格式无效'}});return;}res.status(500).json({error:{code:'INTERNAL_ERROR',message:'操作失败，请稍后重试'}});});
 return app;
}
