import {randomUUID,createHash} from 'node:crypto';
import type {CaseRecord,Evidence} from '../shared/types.js';
export function newCase(ownerId:string,title:string,description=''):CaseRecord {const now=new Date().toISOString();return {id:randomUUID(),ownerId,title,merchant:'',product:'',amount:'',purchaseDate:'',request:description,category:'',status:'active',demo:false,factRevision:0,members:['butler'],facts:[],evidence:[],messages:[],tasks:[],drafts:[],runs:[],createdAt:now,updatedAt:now};}
export function demoCase(owner:string,scenario:string){const timestamp=new Date().toISOString();const c=newCase(owner,`示例：${scenario==='contradiction'?'商家说法待核对':scenario==='evidence-missing'?'补充证据':scenario==='continue'?'持续跟进':'退款协商'}`,'本案为预制示例，不构成真实售后或识别结果');c.demo=true;c.product='示例耳机';c.amount='199';c.merchant='示例店铺';c.purchaseDate='2026-10-01';c.request=scenario==='continue'?'示例：已发起售后，等待商家明确回复':scenario==='evidence-missing'?'示例：商品故障，缺少订单原件，希望补充材料后协商':'示例：耳机到货后出现杂音，希望协商退款';
 const addEvidence=(filename:string,sourceText:string)=>{const e:Evidence={id:randomUUID(),code:'E'+(c.evidence.length+1),filename,mime:'text/plain',size:Buffer.byteLength(sourceText),sha256:createHash('sha256').update(sourceText).digest('hex'),sourceType:'text',sourceText,confirmed:false,createdAt:timestamp};c.evidence.push(e);return e;};
 c.messages.push({id:randomUUID(),role:'system',content:'预制演示案件。所有人物、商家和材料均为示例，上传新材料不会生成伪识别结果。',citations:[],createdAt:timestamp,mode:'demo'});
 if(scenario!=='evidence-missing')addEvidence('示例订单.txt','【虚构示例】商品：耳机；金额：199元；购买日期：2026-10-01；订单号：DEMO-ORDER-001。');
 const e=scenario==='contradiction'?addEvidence('示例商家沟通.txt','【虚构示例】客服甲：同意退款，请退回商品。客服乙：不予退款，不接受退回。'):scenario==='continue'?addEvidence('示例跟进回复.txt','【虚构示例】客服：已收到售后申请，核对后回复。'):scenario==='refund'?addEvidence('示例售后承诺.txt','【虚构示例】客服：请提供订单及故障说明，核对后协商退款。'):undefined;
 const quote=scenario==='contradiction'?'同意退款，请退回商品':scenario==='continue'?'已收到售后申请，核对后回复':'请提供订单及故障说明，核对后协商退款';
 if(e){c.facts.push({id:randomUUID(),label:'商家沟通（示例待核对）',value:quote,status:'proposed',origin:'user',evidenceId:e.id,quote,revision:1});c.factRevision=1;}
 const agentId=scenario==='contradiction'?'detective':scenario==='continue'?'followup':scenario==='evidence-missing'?'analyst':'refund';const content=scenario==='contradiction'?'示例中的两段回复对是否接受退款存在差异，请核对是否同一订单、相同条件及完整上下文后再判断。':scenario==='continue'?'示例显示售后申请已受理，尚无明确处理结果。建议确认回复期限并保留后续沟通。':scenario==='evidence-missing'?'示例缺少订单及故障材料，先补充购买凭证和问题原始记录，不能凭描述认定责任。':'示例建议先核对订单及故障说明，再向商家提出明确退款诉求，不保证退款成功。';
 c.members=['butler',agentId];c.messages.push({id:randomUUID(),role:'agent',agentId,content,citations:e?[{evidenceId:e.id,quote}]:[],createdAt:timestamp,mode:'demo'});c.tasks.push({id:randomUUID(),title:scenario==='continue'?'确认商家回复期限（示例）':scenario==='contradiction'?'核对两段回复是否针对同一订单（示例）':scenario==='evidence-missing'?'补充原始订单与故障记录（示例）':'核对订单后提出明确售后诉求（示例）',agentId,priority:'normal',status:'proposed',createdAt:timestamp});if(scenario==='refund'||scenario==='continue')c.drafts.push({id:randomUUID(),tone:'gentle',text:'【示例草稿】您好，请确认本次售后的处理方案及预计回复时间。我会补充经核对的订单和问题材料。',factRevision:c.factRevision,stale:false,createdAt:timestamp});return c;
}
