import {it,expect} from 'vitest';
import {createApp} from '../src/server/app.js';
import request from 'supertest';
import sharp from 'sharp';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const h={'X-WhyDuck-Client':'web'};
const result={agentId:'analyst',message:'待核对',facts:[],tasks:[],drafts:[],citations:[],missingEvidence:[],suggestedMembers:[]};
it('私有原图字节与输入SHA一致，异步验证中的并发上传均保留',async()=>{const dir=mkdtempSync(join(tmpdir(),'wd-raw-'));const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost',disableRateLimit:true}));const client=request.agent(app);try{await client.post('/api/auth/register').set(h).send({email:'raw@example.test',password:'Safe-password-123456'});const id=(await client.post('/api/cases').set(h).send({title:'原图'})).body.case.id;const bytes=await sharp({create:{width:120,height:120,channels:3,background:'#ffd65a'}}).png().withMetadata().toBuffer();const uploads=await Promise.all([client.post(`/api/cases/${id}/evidence`).set(h).attach('file',bytes,{filename:'a.png',contentType:'image/png'}),client.post(`/api/cases/${id}/evidence`).set(h).attach('file',bytes,{filename:'b.png',contentType:'image/png'})]);expect(uploads.map(r=>r.status)).toEqual([201,201]);const c=(await client.get(`/api/cases/${id}`)).body.case;expect(c.evidence).toHaveLength(2);expect(new Set(c.evidence.map((e:any)=>e.code)).size).toBe(2);const file=await client.get(`/api/cases/${id}/evidence/${c.evidence[0].id}/file`).buffer(true).parse((res,done)=>{const chunks:Buffer[]=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>done(null,Buffer.concat(chunks)))});expect(createHash('sha256').update(file.body).digest('hex')).toBe(createHash('sha256').update(bytes).digest('hex'));expect(c.evidence[0].sha256).toBe(createHash('sha256').update(bytes).digest('hex'));const encoded=await client.get(`/api/cases/${id}/evidence/${c.evidence[0].id}/file?encoding=base64&offset=0`);expect(encoded.status).toBe(200);expect(Buffer.from(encoded.body.base64,'base64')).toEqual(bytes);expect(encoded.body.nextOffset).toBeNull();expect(encoded.headers['cache-control']).toBe('private, no-store');expect((await request(app).get(`/api/cases/${id}/evidence/${c.evidence[0].id}/file?encoding=base64`)).status).toBe(401);expect((await client.get(`/api/cases/${id}/evidence/${c.evidence[0].id}/file?encoding=base64&offset=-1`)).status).toBe(400);}finally{app.locals.db.close();rmSync(dir,{recursive:true,force:true})}});
it('LOCAL MOCK HTTP: 真实SSE取消落库且释放锁，旧run不能取消新workflow',async()=>{
 let delay=false;const model=createServer(async(req,res)=>{for await(const _ of req){}if(delay){await new Promise<void>(resolve=>{const t=setTimeout(resolve,2000);res.on('close',()=>{clearTimeout(t);resolve()})});}if(!res.destroyed){res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(result)}}]}));}});await new Promise<void>(r=>model.listen(0,'127.0.0.1',r));process.env.DASHSCOPE_API_KEY='local-test';process.env.QWEN_BASE_URL=`http://127.0.0.1:${(model.address() as any).port}/v1`;const dir=mkdtempSync(join(tmpdir(),'wd-cancel-'));const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost',disableRateLimit:true}));const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as any).port}`;let cookie='';const call=async(path:string,body?:unknown,method='POST')=>fetch(base+path,{method,headers:{...h,'Content-Type':'application/json',Cookie:cookie},...(body===undefined?{}:{body:JSON.stringify(body)})});
 try{const registration=await call('/api/auth/register',{email:'cancel@example.test',password:'Safe-password-123456'});cookie=registration.headers.get('set-cookie')!.split(';')[0];await call('/api/profile',{aiConsent:true},'PATCH');const id=(await (await call('/api/cases',{title:'取消'})).json()).case.id;const first=await call(`/api/cases/${id}/messages`,{message:'第一轮',target:'analyst',mode:'direct'});await first.text();let c=(await(await call(`/api/cases/${id}`,undefined,'GET')).json()).case;const oldId=c.runs[0].id;delay=true;
 const response=await call(`/api/cases/${id}/messages`,{message:'第二轮',target:'analyst',mode:'direct'});const reader=response.body!.getReader();let raw='';while(!raw.includes('"type":"start"')){const chunk=await reader.read();if(chunk.done)throw new Error('missing start');raw+=new TextDecoder().decode(chunk.value);}const start=raw.split('\n').filter(line=>line.startsWith('data:')).map(line=>JSON.parse(line.slice(5))).find(e=>e.type==='start');expect((await call(`/api/cases/${id}/runs/${oldId}/cancel`)).status).toBe(404);expect((await call(`/api/cases/${id}`,{title:'锁内修改'},'PATCH')).status).toBe(409);expect((await call(`/api/cases/${id}/runs/${start.runId}/cancel`)).status).toBe(200);while(true){const chunk=await reader.read();if(chunk.done)break;raw+=new TextDecoder().decode(chunk.value);}expect(raw).toContain('"type":"cancelled"');c=(await(await call(`/api/cases/${id}`,undefined,'GET')).json()).case;expect(c.runs.at(-1).status).toBe('cancelled');expect(c.messages.filter((m:any)=>m.role==='agent')).toHaveLength(1);delay=false;expect((await call(`/api/cases/${id}`,{title:'锁已释放'},'PATCH')).status).toBe(200);const next=await call(`/api/cases/${id}/messages`,{message:'第三轮',target:'analyst',mode:'direct'});expect(await next.text()).toContain('"type":"done"');
 }finally{await new Promise<void>(r=>server.close(()=>r()));app.locals.db.close();rmSync(dir,{recursive:true,force:true});delete process.env.DASHSCOPE_API_KEY;delete process.env.QWEN_BASE_URL;await new Promise<void>(r=>model.close(()=>r()))}
},10000);
it('LOCAL MOCK HTTP: MCP业务服务新图extract真实调用视觉并持久化待核对结果',async()=>{let body:any;const bodies:any[]=[];const model=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;body=JSON.parse(raw);bodies.push(body);res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(body.model==='qwen-vl-max'?{extractions:[{evidenceId:evidenceId,data:{amount:'199',quotes:['订单金额199'],uncertainties:['需人工核对']}}]}:{...result,agentId:'detective',extractions:[]})}}]}));});let evidenceId='';await new Promise<void>(r=>model.listen(0,'127.0.0.1',r));process.env.DASHSCOPE_API_KEY='local-test';process.env.QWEN_BASE_URL=`http://127.0.0.1:${(model.address() as any).port}/v1`;const dir=mkdtempSync(join(tmpdir(),'wd-mcpvision-'));const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost',disableRateLimit:true}));const client=request.agent(app);try{const user=(await client.post('/api/auth/register').set(h).send({email:'vision@example.test',password:'Safe-password-123456'})).body.user;const id=(await client.post('/api/cases').set(h).send({title:'视觉'})).body.case.id;const bytes=await sharp({create:{width:100,height:100,channels:3,background:'#ffd65a'}}).png().toBuffer();evidenceId=(await client.post(`/api/cases/${id}/evidence`).set(h).attach('file',bytes,{filename:'a.png',contentType:'image/png'})).body.evidence.id;await expect(app.locals.services.executeTool('extract_purchase_evidence',{evidenceId},{userId:user.id,caseId:id})).rejects.toThrow(/同意/);await client.patch('/api/profile').set(h).send({aiConsent:true});const extracted=await app.locals.services.executeTool('extract_purchase_evidence',{evidenceId},{userId:user.id,caseId:id});expect(extracted.status).toBe('proposed');expect(extracted.extraction.amount).toBe('199');const visionBody=bodies.find(b=>b.model==='qwen-vl-max');expect(visionBody).toBeTruthy();expect(body.model).toBe('qwen-plus');expect(visionBody.messages.at(-1).content.some((v:any)=>v.type==='image_url')).toBe(true);const c=(await client.get(`/api/cases/${id}`)).body.case;expect(c.evidence[0].confirmed).toBe(false);expect(c.evidence[0].extraction.amount).toBe('199');expect(c.runs[0].agentId).toBe('detective');expect(c.messages.filter((m:any)=>m.role==='user')).toHaveLength(0);}finally{app.locals.db.close();rmSync(dir,{recursive:true,force:true});delete process.env.DASHSCOPE_API_KEY;delete process.env.QWEN_BASE_URL;await new Promise<void>(r=>model.close(()=>r()))}});
it('支付宝身份唯一且冲突不改变原有关联；报告保留消息级引用与运行来源',async()=>{const dir=mkdtempSync(join(tmpdir(),'wd-unique-report-'));const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost',disableRateLimit:true}));const a=request.agent(app),b=request.agent(app);try{const one=(await a.post('/api/auth/register').set(h).send({email:'one@example.test',password:'Safe-password-123456'})).body.user;const two=(await b.post('/api/auth/register').set(h).send({email:'two@example.test',password:'Safe-password-123456'})).body.user;(await app.locals.services.linkAlipay(one.id,'shared-alipay-id'));await expect(app.locals.services.linkAlipay(two.id,'shared-alipay-id')).rejects.toThrow(/已关联/);expect((await app.locals.db.prepare('SELECT alipay FROM users WHERE id=?').get(two.id)).alipay).toBeNull();const c=(await a.post('/api/cases/demo').set(h).send({scenario:'contradiction'})).body.case;const report=await a.get(`/api/cases/${c.id}/report?format=markdown`);expect(report.text).toContain('据理力争鸭');expect(report.text).toContain('逐字引文：同意退款，请退回商品');expect(report.text).toContain('E2 示例商家沟通.txt');expect(report.text).toContain('SHA-256');expect(report.text).toContain('用户沟通与AI协作时间线');const file=await a.get(`/api/cases/${c.id}/evidence/${c.evidence[0].id}/file`);expect(file.status).toBe(200);expect(file.text).toContain('虚构示例');await a.delete(`/api/cases/${c.id}/evidence/${c.evidence[1].id}`).set(h).send({confirmation:c.evidence[1].id});expect((await a.get(`/api/cases/${c.id}/report`)).text).toContain('来源已移除');}finally{app.locals.db.close();rmSync(dir,{recursive:true,force:true})}});
it('认证限流只计算敏感写请求，读取令牌不消耗登录额度',async()=>{const dir=mkdtempSync(join(tmpdir(),'wd-rate-'));const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost'}));const client=request.agent(app);try{const credentials={email:'rate@example.test',password:'Safe-password-123456'};await client.post('/api/auth/register').set(h).send(credentials).expect(201);for(let i=0;i<30;i++)await client.get('/api/auth/tokens').expect(200);await client.post('/api/auth/login').set(h).send(credentials).expect(200);let last=0;for(let i=0;i<26;i++)last=(await client.post('/api/auth/login').set(h).send(credentials)).status;expect(last).toBe(429);}finally{app.locals.db.close();rmSync(dir,{recursive:true,force:true})}},10000);
