import {describe,it,expect} from 'vitest';
import express from 'express';
import multer from 'multer';
// Deployment entries are JavaScript platform contracts, independently exercised locally.
// @ts-ignore no declaration is needed for deployment-only adapter
import {expressWeb} from '../cloud-functions/_whyduck/express-web.js';
// @ts-ignore deployment-only Web entry
import cloudEntry,{onRequest,createRequestHandler} from '../cloud-functions/api/[[default]].js';
// @ts-ignore platform-only entry
import {onRequest as agentEntry} from '../agents/whyduck/index.js';
// @ts-ignore bundled module is generated by build-edgeone.mjs
import {configurationErrors,createCloudRuntime} from '../cloud-functions/_whyduck/runtime.js';

describe('EdgeOne Web/Express adapter',()=>{
 it('accepts the real parsed AgentContextRequest contract',async()=>{
  const original=process.env.EVIDENCE_STORAGE;delete process.env.EVIDENCE_STORAGE;
  const id='3a0657a7-4f79-44fb-8629-2fafd3cb1d2a';
  try {const response=await agentEntry({request:{method:'POST',url:'https://example.test/whyduck?path='+encodeURIComponent('/api/cases/'+id+'/messages'),headers:{'content-type':'application/json','makers-conversation-id':id},body:{message:'test',mode:'group'},signal:new AbortController().signal,eo:{clientIp:'203.0.113.7'}}});expect(response.status).toBe(503);expect((await response.json()).error.code).toBe('CLOUD_UNCONFIGURED');}finally{if(original!==undefined)process.env.EVIDENCE_STORAGE=original;}
 });
 it('retains report query options through the deployed handler contract',async()=>{
  const app=express();app.get('/api/report',(req,res)=>res.json(req.query));const handler=createRequestHandler(app);
  const response=await handler({request:new Request('https://example.test/api/report?format=markdown&redact=true')});expect(await response.json()).toEqual({format:'markdown',redact:'true'});
 });
 it('preserves multipart upload bytes through the Web bridge',async()=>{
  const app=express();app.post('/api/upload',multer({storage:multer.memoryStorage()}).single('file'),(req,res)=>res.json({bytes:req.file!.buffer.toString('base64'),mime:req.file!.mimetype}));
  const form=new FormData();const bytes=new Uint8Array([137,80,78,71,0,255,0,128]);form.set('file',new Blob([bytes],{type:'image/png'}),'test.png');
  const response=await expressWeb(app,new Request('https://example.test/api/upload',{method:'POST',body:form}),'/api/upload');expect(await response.json()).toEqual({bytes:Buffer.from(bytes).toString('base64'),mime:'image/png'});
 });
 it('uses only the trusted platform client IP rather than forwarded headers',async()=>{
  const app=express();app.get('/api/ip',(req,res)=>res.json({ip:req.ip,forwarded:req.headers['x-forwarded-for']??null}));
  const response=await expressWeb(app,new Request('https://example.test/api/ip',{headers:{'x-forwarded-for':'198.51.100.88'}}),'/api/ip','203.0.113.7');expect(await response.json()).toEqual({ip:'203.0.113.7',forwarded:null});
 });
 it('invokes the actual Cloud Functions Web entry without an app.fetch contract',async()=>{
  const original=process.env.EVIDENCE_STORAGE;delete process.env.EVIDENCE_STORAGE;
  try {for(const response of [await onRequest({request:new Request('https://example.test/api/health'),clientIp:'127.0.0.1'}),await cloudEntry.fetch(new Request('https://example.test/api/health'))]){expect(response.status).toBe(503);expect((await response.json()).error.code).toBe('CLOUD_UNCONFIGURED');}}finally{if(original!==undefined)process.env.EVIDENCE_STORAGE=original;}
 });
 it('preserves the original API path, status, headers and cookies',async()=>{
  const app=express();app.post('/api/cases/abc/messages',express.json(),(req,res)=>{res.status(201).cookie('whyduck_session','test',{httpOnly:true,secure:true}).set('X-Test','yes').json({path:req.originalUrl,body:req.body});});
  const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST',headers:{'content-type':'application/json'},body:'{"message":"hello"}'}),'/api/cases/abc/messages');
  expect(response.status).toBe(201);expect(response.headers.get('x-test')).toBe('yes');expect(response.headers.get('set-cookie')).toContain('HttpOnly');expect(await response.json()).toEqual({path:'/api/cases/abc/messages',body:{message:'hello'}});
 });
 it('delivers streamed chunks before the request ends',async()=>{
  const app=express();let end:()=>void=()=>{};app.post('/api/test',(_req,res)=>{res.set('Content-Type','text/event-stream');res.flushHeaders();res.write('data: one\n\n');end=()=>res.end('data: two\n\n');});
  const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST'}),'/api/test');const reader=response.body!.getReader();const first=await reader.read();expect(new TextDecoder().decode(first.value)).toBe('data: one\n\n');end();expect(new TextDecoder().decode((await reader.read()).value)).toBe('data: two\n\n');expect((await reader.read()).done).toBe(true);
 });
 it('propagates response cancellation as close',async()=>{
  const app=express();let closed=false;app.post('/api/test',(_req,res)=>{res.on('close',()=>{closed=true;});res.flushHeaders();});const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST'}),'/api/test');await response.body!.cancel();expect(closed).toBe(true);
 });
 it('fails closed before app creation without cloud configuration',async()=>{
  const original=process.env.EVIDENCE_STORAGE;delete process.env.EVIDENCE_STORAGE;
  try {const response=await expressWeb(createCloudRuntime(),new Request('https://example.test/api/session'),'/api/session');expect(response.status).toBe(503);expect((await response.json()).error.code).toBe('CLOUD_UNCONFIGURED');}finally{if(original!==undefined)process.env.EVIDENCE_STORAGE=original;}
 });
 it('rejects local DB URLs, missing tokens, HTTP origin and malformed encryption keys',()=>{
  expect(configurationErrors({TURSO_DATABASE_URL:'file:tmp.db',PUBLIC_ORIGIN:'http://localhost',EVIDENCE_STORAGE:'local',EVIDENCE_ENCRYPTION_KEY:'invalid'})).toEqual(expect.arrayContaining(['TURSO_AUTH_TOKEN','TURSO_DATABASE_URL(remote)','PUBLIC_ORIGIN(https)','EVIDENCE_STORAGE(edgeone-blob)','EVIDENCE_ENCRYPTION_KEY(32-byte-base64)']));
 });
 it('returns safe initialization failure JSON and permits a later retry',async()=>{
  const values={TURSO_DATABASE_URL:'libsql://example.test',TURSO_AUTH_TOKEN:'synthetic-test-token',PUBLIC_ORIGIN:'https://example.test',EVIDENCE_STORAGE:'edgeone-blob',EVIDENCE_ENCRYPTION_KEY:Buffer.alloc(32).toString('base64')};const old=Object.fromEntries(Object.keys(values).map(key=>[key,process.env[key]]));Object.assign(process.env,values);
  try {let attempts=0;const app=createCloudRuntime(async()=>{attempts++;throw new Error('sensitive connection details');});for(let i=0;i<2;i++){const response=await expressWeb(app,new Request('https://example.test/api/session'),'/api/session');expect(response.status).toBe(503);const text=await response.text();expect(text).toContain('CLOUD_INITIALIZATION_FAILED');expect(text).not.toContain('sensitive');}expect(attempts).toBe(2);}finally{for(const [key,value]of Object.entries(old))if(value===undefined)delete process.env[key];else process.env[key]=value;}
 });
});

it('ends a cancelled Express stream without writing into a closed Web controller',async()=>{
 const app=express();let end:()=>void=()=>{};app.post('/api/test',(_req,res)=>{res.flushHeaders();end=()=>{res.write('late data');res.end();};});
 const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST'}),'/api/test');await response.body!.cancel();expect(end).not.toThrow();
});
