import {describe,it,expect} from 'vitest';
import express from 'express';
// Deployment entries are JavaScript platform contracts, independently exercised locally.
// @ts-ignore no declaration is needed for deployment-only adapter
import {expressWeb} from '../cloud-functions/_whyduck/express-web.js';
// @ts-ignore deployment-only Web entry
import {onRequest} from '../cloud-functions/api/[[default]].js';
// @ts-ignore bundled module is generated by build-edgeone.mjs
import {configurationErrors,createCloudRuntime} from '../cloud-functions/_whyduck/runtime.js';

describe('EdgeOne Web/Express adapter',()=>{
 it('invokes the actual Cloud Functions Web entry without an app.fetch contract',async()=>{
  const original=process.env.EVIDENCE_STORAGE;delete process.env.EVIDENCE_STORAGE;
  try {const response=await onRequest({request:new Request('https://example.test/api/health'),clientIp:'127.0.0.1'});expect(response.status).toBe(503);expect((await response.json()).error.code).toBe('CLOUD_UNCONFIGURED');}finally{if(original!==undefined)process.env.EVIDENCE_STORAGE=original;}
 });
 it('preserves the original API path, status, headers and cookies',async()=>{
  const app=express();app.post('/api/cases/abc/messages',express.json(),(req,res)=>{res.status(201).cookie('whyduck_session','test',{httpOnly:true,secure:true}).set('X-Test','yes').json({path:req.originalUrl,body:req.body});});
  const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST',headers:{'content-type':'application/json'},body:'{"message":"hello"}'}),'/api/cases/abc/messages');
  expect(response.status).toBe(201);expect(response.headers.get('x-test')).toBe('yes');expect(response.headers.get('set-cookie')).toContain('HttpOnly');expect(await response.json()).toEqual({path:'/api/cases/abc/messages',body:{message:'hello'}});
 });
 it('delivers streamed chunks before the request ends',async()=>{
  const app=express();let end:()=>void=()=>{};app.post('/api/test',(_req,res)=>{res.set('Content-Type','text/event-stream');res.flushHeaders();res.write('data: one\n\n');end=()=>res.end('data: two\n\n');});
  const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST'}),'/api/test');const reader=response.body!.getReader();const first=await reader.read();expect(new TextDecoder().decode(first.value)).toBe('data: one\n\n');end();expect(new TextDecoder().decode((await reader.read()).value)).toBe('data: two\n\n');expect((await reader.read()).done).toBe(true);
 });
 it('propagates response cancellation as close',async()=>{
  const app=express();let closed=false;app.post('/api/test',(_req,res)=>{res.on('close',()=>{closed=true;});res.flushHeaders();});const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST'}),'/api/test');await response.body!.cancel();expect(closed).toBe(true);
 });
 it('fails closed before app creation without cloud configuration',async()=>{
  const original=process.env.EVIDENCE_STORAGE;delete process.env.EVIDENCE_STORAGE;
  try {const response=await expressWeb(createCloudRuntime(),new Request('https://example.test/api/session'),'/api/session');expect(response.status).toBe(503);expect((await response.json()).error.code).toBe('CLOUD_UNCONFIGURED');}finally{if(original!==undefined)process.env.EVIDENCE_STORAGE=original;}
 });
 it('rejects local DB URLs, missing tokens, HTTP origin and malformed encryption keys',()=>{
  expect(configurationErrors({TURSO_DATABASE_URL:'file:tmp.db',PUBLIC_ORIGIN:'http://localhost',EVIDENCE_STORAGE:'local',EVIDENCE_ENCRYPTION_KEY:'invalid'})).toEqual(expect.arrayContaining(['TURSO_AUTH_TOKEN','TURSO_DATABASE_URL(remote)','PUBLIC_ORIGIN(https)','EVIDENCE_STORAGE(edgeone-blob)','EVIDENCE_ENCRYPTION_KEY(32-byte-base64)']));
 });
 it('returns safe initialization failure JSON and permits a later retry',async()=>{
  const values={TURSO_DATABASE_URL:'libsql://example.test',TURSO_AUTH_TOKEN:'synthetic-test-token',PUBLIC_ORIGIN:'https://example.test',EVIDENCE_STORAGE:'edgeone-blob',EVIDENCE_ENCRYPTION_KEY:Buffer.alloc(32).toString('base64')};const old=Object.fromEntries(Object.keys(values).map(key=>[key,process.env[key]]));Object.assign(process.env,values);
  try {let attempts=0;const app=createCloudRuntime(async()=>{attempts++;throw new Error('sensitive connection details');});for(let i=0;i<2;i++){const response=await expressWeb(app,new Request('https://example.test/api/session'),'/api/session');expect(response.status).toBe(503);const text=await response.text();expect(text).toContain('CLOUD_INITIALIZATION_FAILED');expect(text).not.toContain('sensitive');}expect(attempts).toBe(2);}finally{for(const [key,value]of Object.entries(old))if(value===undefined)delete process.env[key];else process.env[key]=value;}
 });
});

it('ends a cancelled Express stream without writing into a closed Web controller',async()=>{
 const app=express();let end:()=>void=()=>{};app.post('/api/test',(_req,res)=>{res.flushHeaders();end=()=>{res.write('late data');res.end();};});
 const response=await expressWeb(app,new Request('https://example.test/whyduck',{method:'POST'}),'/api/test');await response.body!.cancel();expect(end).not.toThrow();
});
