import {describe,it,expect} from 'vitest';
import request from 'supertest';
import {createServer} from 'node:http';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../src/server/app.js';
const headers={'X-WhyDuck-Client':'web'};
const out=(agentId:string)=>({agentId,message:'基于待核对材料的建议',facts:[],tasks:[],drafts:[],citations:[],missingEvidence:[],suggestedMembers:[]});
describe('LOCAL MOCK HTTP 模型与实际业务 SSE 集成',()=>{
 it('真实REST产生SSE并持久化角色提案，严格target且拒绝未授权AI',async()=>{
  let calls=0;const server=createServer(async(req,res)=>{for await(const _ of req){}calls++;res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({...out('analyst'),facts:[{label:'用户诉求',value:'待核对退款'}]})}}]}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const dir=mkdtempSync(join(tmpdir(),'wd-sse-'));process.env.DASHSCOPE_API_KEY='local-test';process.env.QWEN_BASE_URL=`http://127.0.0.1:${(server.address() as any).port}/v1`;const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost',disableRateLimit:true}));const client=request.agent(app);
  try{await client.post('/api/auth/register').set(headers).send({email:'sse@example.test',password:'Safe-test-password-123',name:'SSE'}).expect(201);const c=(await client.post('/api/cases').set(headers).send({title:'退款'})).body.case;await client.post(`/api/cases/${c.id}/messages`).set(headers).send({message:'分析',mode:'direct',target:'analyst'}).expect(403);expect(calls).toBe(0);await client.patch('/api/profile').set(headers).send({aiConsent:true});const sse=await client.post(`/api/cases/${c.id}/messages`).set(headers).send({message:'分析',mode:'group',target:'analyst'}).expect(200);expect(sse.headers['content-type']).toContain('text/event-stream');expect(sse.text).toContain('"type":"result"');const after=(await client.get(`/api/cases/${c.id}`)).body.case;expect(after.runs[0].status).toBe('completed');expect(after.facts[0].status).toBe('proposed');expect(after.runs[0].dependsOn).toEqual([]);expect(calls).toBe(1);}finally{app.locals.db.close();rmSync(dir,{recursive:true,force:true});delete process.env.DASHSCOPE_API_KEY;delete process.env.QWEN_BASE_URL;await new Promise<void>(r=>server.close(()=>r()))}
 });
 it('重试失败角色使用原始任务，后续用户消息不污染重试',async()=>{
  let calls=0;const bodies:any[]=[];const server=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;bodies.push(JSON.parse(raw));calls++;res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{content:calls<=2?JSON.stringify({...out('analyst'),citations:[{evidenceId:'unknown',quote:'fabricated'}]}):JSON.stringify(out('analyst'))}}]}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const dir=mkdtempSync(join(tmpdir(),'wd-retry-'));process.env.DASHSCOPE_API_KEY='local-test';process.env.QWEN_BASE_URL=`http://127.0.0.1:${(server.address() as any).port}/v1`;const app=(await createApp({dataDir:dir,publicOrigin:'http://localhost',disableRateLimit:true}));const client=request.agent(app);
  try{await client.post('/api/auth/register').set(headers).send({email:'retry@example.test',password:'Safe-test-password-123',name:'Retry'});await client.patch('/api/profile').set(headers).send({aiConsent:true});const c=(await client.post('/api/cases').set(headers).send({title:'退款'})).body.case;await client.post(`/api/cases/${c.id}/messages`).set(headers).send({message:'原始售后任务',mode:'direct',target:'analyst'});const failed=(await client.get(`/api/cases/${c.id}`)).body.case.runs[0];expect(failed.status).toBe('failed');await client.post(`/api/cases/${c.id}/messages`).set(headers).send({message:'后续不同问题',mode:'direct',target:'analyst'});await client.post(`/api/cases/${c.id}/retry`).set(headers).send({runId:failed.id}).expect(200);const input=JSON.parse(bodies[3].messages[1].content);expect(input.message).toBe('原始售后任务');const after=(await client.get(`/api/cases/${c.id}`)).body.case;expect(after.messages.filter((m:any)=>m.role==='user')).toHaveLength(2);}finally{app.locals.db.close();rmSync(dir,{recursive:true,force:true});delete process.env.DASHSCOPE_API_KEY;delete process.env.QWEN_BASE_URL;await new Promise<void>(r=>server.close(()=>r()))}
 });
});
