// Real browser + live configured provider. Synthetic material only; no mocks.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/lucianaib/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const sharp=require('sharp');
const out=path.resolve('artifacts/acceptance');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:1000}});
 const report={checkedAt:new Date().toISOString(),syntheticDataOnly:true,provider:'live configured Qwen',checks:[],errors:[],alipay:'explicitly skipped'};
 page.on('pageerror',e=>report.errors.push(e.message));
 const visit=async r=>{await page.goto('http://127.0.0.1:5173/#'+r);await page.waitForFunction(()=>document.querySelector('.main')&&!document.querySelector('.main .spinner'));};
 const current=()=>page.evaluate(async()=>{const r=await fetch('/api/cases/'+sessionStorage.getItem('whyduck-case'));if(!r.ok)throw Error('case HTTP '+r.status);return (await r.json()).case});
 const send=async(message)=>{await page.getByLabel('聊天消息').fill(message);const response=page.waitForResponse(r=>r.url().endsWith('/messages')&&r.request().method()==='POST',{timeout:20000});await page.getByRole('button',{name:'发送',exact:true}).click();const r=await response;assert.equal(r.status(),200);await page.getByRole('button',{name:'发送',exact:true}).waitFor({timeout:300000});console.log('LIVE_SEND_COMPLETED');await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).some(b=>b.textContent.includes('取消本次')),{timeout:300000});const c=await current();const failed=c.runs.filter(r=>r.status==='failed');assert.equal(failed.length,0,JSON.stringify(failed));return c;};
 try{
  await visit('register');await page.getByLabel('昵称',{exact:true}).fill('真实验收合成账户');await page.getByLabel('邮箱',{exact:true}).fill('live-'+Date.now()+'@example.test');await page.getByLabel('密码',{exact:true}).fill('Synthetic-acceptance-2026!');await page.getByRole('button',{name:'注册并登录',exact:true}).click();await page.getByLabel('描述售后问题').waitFor();
  await page.getByLabel('描述售后问题').fill('合成验收：测试耳机199元，商家承诺收到退货后三天退款，但尚未收到退款。请协助退款沟通与后续跟进。');await page.getByRole('button',{name:'创建案件',exact:true}).click();await page.getByLabel('聊天消息').waitFor();await visit('settings');await page.getByLabel('同意 AI 材料处理').click();await page.waitForFunction(()=>document.querySelector('[aria-label="同意 AI 材料处理"]').checked);await visit('home');await page.getByRole('button',{name:'找管家鸭帮忙 →',exact:true}).click();
  let c=await send('这是合成验收。退款未到账，请自动选择专业鸭分析退款问题、生成协商草稿并安排跟进。');await page.waitForURL('**/#meeting');report.checks.push('homepage → butler → automatic real collaboration → meeting');
  await visit('evidence');const imagePath=path.join(out,'synthetic-order.png');await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="600"><rect width="100%" height="100%" fill="white"/><g font-family="sans-serif" font-size="42"><text x="40" y="80">SYNTHETIC TEST ORDER</text><text x="40" y="180">Merchant: Test Shop</text><text x="40" y="270">Product: Test Earbuds</text><text x="40" y="360">Amount: CNY 199.00</text><text x="40" y="450">Date: 2026-10-08</text><text x="40" y="540">Order: TEST-ACCEPTANCE-001</text></g></svg>')).png().toFile(imagePath);await page.getByLabel('上传材料').setInputFiles(imagePath);await page.waitForFunction(()=>!document.querySelector('progress'));
  await page.getByLabel('粘贴原始沟通记录').fill('商家原文：收到退货后三天内处理退款。合成测试订单 TEST-ACCEPTANCE-001，退款199元。');await page.getByRole('button',{name:'保存原始记录',exact:true}).click();await page.waitForTimeout(500);
  await visit('meeting');c=await send('请核对刚上传的订单截图及商家原文证据，据理力争鸭提取订单并引用原文，退款鸭生成沟通方案，后手鸭创建跟进建议，管家汇总最终办事单。');
  assert.equal(c.demo,false);const vision=c.evidence.find(e=>e.sourceType==='image');assert(vision?.extraction?.amount?.includes('199'),'real vision extracted amount');assert(c.drafts.length>0,'refund draft persisted');assert.equal(c.drafts.at(-1).stale,false,'latest refund draft stays usable after followup');assert(c.tasks.some(t=>t.agentId==='followup'),'followup task persisted');for(const role of ['butler','detective','refund','followup'])assert(c.runs.some(r=>r.agentId===role&&r.status==='completed'&&r.inputTokens>0&&r.tools.length),'separate real role and actual tools '+role);assert.equal(c.messages.at(-1).agentId,'butler');
  const citations=c.messages.flatMap(m=>m.citations);assert(citations.length>0,'at least one real source citation');for(const cite of citations){const e=c.evidence.find(e=>e.id===cite.evidenceId);assert((e.sourceText||(e.confirmed?e.extraction.quotes.join('\n'):'' )).includes(cite.quote),'verbatim original citation');}report.checks.push('real image extraction 199, original citations, separate role calls, executed business tools, shared drafts/tasks, final butler summary');
  await page.screenshot({path:path.join(out,'live-meeting-desktop.png'),fullPage:true});const before=JSON.stringify({id:c.id,evidence:c.evidence,messages:c.messages,tasks:c.tasks,drafts:c.drafts});await page.reload();await page.getByLabel('聊天消息').waitFor();c=await current();assert.equal(JSON.stringify({id:c.id,evidence:c.evidence,messages:c.messages,tasks:c.tasks,drafts:c.drafts}),before);report.checks.push('refresh restores exact persisted case, evidence, messages, tasks, drafts');
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'办事单',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'live-meeting-mobile.png'),fullPage:true});report.checks.push('390px mobile real case worklist usable');report.case=c;report.status='passed';assert.deepEqual(report.errors,[]);
 }catch(e){report.status='failed';report.failure=e.message.slice(0,4000);await page.screenshot({path:path.join(out,'live-failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'live-flow.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks,failure:report.failure}));await browser.close();}
})();
